# Generated by Django 5.0.7 on 2024-07-17 13:04

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    choices=[
                        ('untracked', 'File not tracked on storage backend'),
                        ('loaded', 'File load and exsist on storage backend'),
                        ('deleted', 'File exsist, but not tracked on storage backend'),
                        ('on_error', 'Some error with file (probably missing on storge backend)'),
                    ],
                    max_length=32,
                    unique=True,
                )),
                ('description', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('extension', models.CharField(max_length=32)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_data', models.CharField(max_length=256)),
                ('minio_key', models.CharField()),
                ('other', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(
                    default=files.models.FileMetadataStatusManager.get_default_status,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='files.filemetadatastatus',
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
