# Generated by Django 5.0.6 on 2024-06-13 13:38

import django.db.models.deletion
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='size_bytes',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='status',
            field=models.ForeignKey(default=files.models.FileMetadataStatus.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='files.filemetadatastatus'),
        ),
    ]
