# Generated by Django 5.0.6 on 2024-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_filemetadata_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='last_used',
        ),
        migrations.AlterField(
            model_name='filemetadatastatus',
            name='title',
            field=models.CharField(choices=[('untracked', 'File not tracked on storage backend'), ('loaded', 'File load and exsist on storage backend'), ('deleted', 'File exsist, but not tracked on storage backend'), ('on_error', 'Some error with file (probably missing on storge backend)')], max_length=32, unique=True),
        ),
    ]
